#!/bin/bash

# A minimalistic init for benchmarking. Inspired by
# http://stackoverflow.com/questions/15277570/simple-replacement-of-init-to-just-start-console
#
# To boot with Ubuntu:
# * collect a list of modules for your system:
#     $ lsmod | cut -f1 -d ' ' | tr '\n' ' '
#   and store resulting list in MODULES variable in this script.
# * copy to /uSingle
# * press 'Shift' during boot
# * press 'e' to edit boot string
# * find line which looks like
#	linux	/boot/vmlinuz root=... ro splash quiet $vt_handoff
# and replace starting with splash:
#   init=/single
#
# TODO:
# * disable unnecessary kernel threads (see check https://www.kernel.org/doc/Documentation/kernel-per-CPU-kthreads.txt)
# * do a system-wide monitoring via `perf record -a'

MODULES='pci_stub vboxpci vboxnetadp vboxnetflt vboxdrv cuse bnep rfcomm bluetooth binfmt_misc nfsd auth_rpcgss nfs_acl nfs lockd sunrpc fscache joydev hid_generic usbhid hid snd_hda_codec_hdmi snd_hda_codec_realtek eeepc_wmi asus_wmi sparse_keymap intel_rapl x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel snd_hda_intel snd_hda_codec snd_hwdep kvm snd_pcm crct10dif_pclmul snd_page_alloc crc32_pclmul snd_seq_midi ghash_clmulni_intel snd_seq_midi_event snd_rawmidi snd_seq aesni_intel snd_seq_device aes_x86_64 snd_timer lrw gf128mul glue_helper ablk_helper snd cryptd parport_pc serio_raw lpc_ich mei_me soundcore mei ppdev i915 drm_kms_helper lp video parport drm mac_hid i2c_algo_bit wmi psmouse ahci r8169 libahci mii'
for m in $MODULES; do
  modprobe $m
done

# Enable filesystems
mount -o rw,remount /
udevd --daemon
mount -a

if test -d /sys/devices/system/cpu/cpufreq; then
  echo >&2 'Please turn off frequency scaling in BIOS'
  exit 1
fi

# Based on https://lopsa.org/content/detecting-whether-hyperthreading-enabled
if ! grep -q ',00000001$' /sys/devices/system/cpu/cpu0/topology/thread_siblings; then
  echo >&2 'Please turn off hyperthreading in BIOS'
  exit 1
fi

# Disable common sources of overhead
echo 0 > /proc/sys/kernel/randomize_va_space
echo 1 > /proc/sys/vm/drop_caches

runtty() {
  while true; do
    #/sbin/getty -8 115200 tty1 vt100
    /sbin/getty --noclear tty1 linux
  done
}

runtty &

while true; do sleep 9999999; done
